#!/usr/bin/env python
bld.make_package('WireCelluBooNE_NUSEL_APP', use='WireCell2dToy WireCellNav EIGEN WireCellData WireCellSignal WireCellTiling WireCellSst WireCellRess WireCellQuickhull WireCellNanoflann lsp BOOST')
