#+TITLE: Aggregation package for Wire Cell packages

* Prerequisites

Some external packages are required as described in this section.  

** Automated installation

It is recommended to use the automated installation method to install the required externals.  Follow the directions in [[https://github.com/BNLIF/wire-cell-externals][wire-cell-externals]] and come back here after setting up your user environment.

** Manual installation

You may provide the external packages yourself.  The definitive list of required packages, their versions and build details are kept in wire-cell-externals [[https://github.com/BNLIF/wire-cell-externals/blob/master/worch.cfg][worch.cfg]] file.  Refer to that for the most up-to-date information on what software is needed.  In summary you will need:

 - ROOT v6 
 - Python 2.7

You will need to set up your run-time environment so that these commands do not fail and give the expected version:

#+BEGIN_EXAMPLE
  $ root -b -q
  ...
  | Welcome to ROOT 6.02/05                http://root.cern.ch |
  ...
  $ python -c 'import ROOT; print ROOT.gROOT.GetVersion()'
  6.02/05
#+END_EXAMPLE

* Building

** Preparing the source

The wire cell source project uses =git-submodules= to bring all the source together:

#+BEGIN_EXAMPLE
  $ git clone git@github.com:BNLIF/wire-cell.git
  $ cd wire-cell
  $ git submodule init
  $ git submodule update

  $ alias waf=`pwd`/waf-tools/waf
#+END_EXAMPLE

** Building 

To configure, build and install the wire cell code do:

#+BEGIN_EXAMPLE
  $ waf --prefix=/path/to/install configure build install
#+END_EXAMPLE

Note: this is not a Worch build - there is no =--orch-config= option.

If you followed the [[https://github.com/BNLIF/wire-cell-externals#single-rooted-install][single rooted install]] pattern then the =/path/to/install= can be =/path/to/single-rooted= and no additional user environment will be needed for run-time and the following command line should succeed:

#+BEGIN_EXAMPLE
  $ python -c 'import ROOT; print ROOT.WireCellData'
  Warning in <TInterpreter::ReadRootmapFile>: class  pair<float,float> found in libCore.so  is already in libWireCellDataDict.so 
  Warning in <TInterpreter::ReadRootmapFile>: class  pair<int,float> found in libCore.so  is already in libWireCellDataDict.so 
  <class 'ROOT.WireCellData'>
#+END_EXAMPLE

If you provided your own externals or used the name/version tree pattern (using environment modules) then you will need to set your environment properly.  Besides the usual =$PATH=, =$LD_LIBRARY_PATH=, etc pointing at =/path/to/install= you may need to set =PYTHONPATH=.  

Independent from how you installed the code, if you have the broken
ROOT packages for Ubuntu installed you will have to set:

#+BEGIN_EXAMPLE
  $ export PYTHONNOUSERSITE=yes
#+END_EXAMPLE


* Developing

Here is what you will do in the act of developing code.

** Rebuilding

To rebuild after hacking on the source just type:

#+BEGIN_EXAMPLE
  $ waf
#+END_EXAMPLE

When ready to install into the configured "prefix" installation area:

#+BEGIN_EXAMPLE
  $ waf install
#+END_EXAMPLE

** New packages

New wire-cell packages can be added easily.

*** Considerations

Wire Cell packages are organized to be easy to create.  It's much better to create many small packages and maybe later merge them than it is to split apart ones which have grown too monolithic.  When thinking about writing some code consider:

 - What other packages will I need?
 - What future packages will need mine?

You may have an idea for a package but in reality it is better split up into others.  Here are reasons to believe your ideas fit into multiple packages:

 - When I describe my expected package functionality I use the word "and".

 - Some other package should use part of my package but the other part is not needed.

If in doubt, make more, smaller packages.

*** Source Package Conventions.

To make them easy to build and aggregate they must follow a layout convention.  

First, each source package should be kept in it's own git repository.  The recommended package naming convention is:

#+BEGIN_EXAMPLE
  wire-cell-NAME
#+END_EXAMPLE

where "=NAME=" is some short identifier of the package's primary purpose.

The contents of the source package must be organized following these sub-directory conventions:

 - =src/= :: C++ source file for libraries with =.cxx= extensions or private headers 
 - =inc/NAME/= :: public/API C++ header files with =.h= extensions
 - =dict/LinkDef.h= :: ROOT linkdef header (for =rootcling= dictionaries)
 - =tests/= :: Unit tests Python (nosetests) files like =test_*.py= or main C++ programs named like =test_*.cxx=.
- =apps/= :: main application(s), one =appname.cxx= file for each app named appname (todo: not yet supported)
- =python/NAME= :: python modules (todo: not yet supported)
- =wscript_build= :: a brief waf file

The =wscript_build= file specifies a name for the binary package (in general similar but not identical to the source package name) and a list of any other packages part of the wire-cell system on which it depends.  For example the =wire-cell-nav= source package builds to a =WireCellNav= binary package and it depends on the =WireCellData= package and so its [[https://github.com/BNLIF/wire-cell-nav/blob/master/wscript_build][=wscript_build=]] file is:

#+BEGIN_SRC python
  bld.make_package('WireCellNav', use='WireCellData')
#+END_SRC

This is Python and the =bld= object is a Waf build context.  It is provided automagically when waf interprets this file.

*** Build packages

The above is about code packages.  Code packages are built via a build package.  This build package, =wire-cell= is but one possible "view" into all the wire cell packages.  Other build packages may be created which only build some sub-set of all wire cell packages.

To add a new code package to a build package one must do the following:

- Create the build package repository
- Create a top level Waf =wscript= file such as [[./wscript][this one]]
- Add the code package(s) as a submodule:

#+BEGIN_EXAMPLE
  $ git submodule add -- git@github.com:BNLIF/wire-cell-<NAME>.git <NAME>
#+END_EXAMPLE 

Where =<NAME>= should be a short identifier for the package which is unique to the build package.

- Add the =<NAME>= to the =subdirs= list in the [[./wscript]] file.

- Commit and push.

*** Namespaces

The namespace =WireCell= is used for all "core" wire cell code.  Code that is used to glue this core functionality into other systems may use another namespace but should not use =WireCell=.  For example, the "simple simulation tree" uses =WireCellSst".

It can be tedious to type explicit namespace qualifiers all the time.  You can use the =using namespace WireCell;=  directive where in implementation files (=*.cxx=) but you should *never* use it in (top-scope) of header files as it will then leak the contents of the namespace into any unsuspecting file that =#include='s it.

*** Tests

Tests go under the =test/= (or =tests/=) sub-directory of the package.  There are two types, C++ and Python.  In both cases, only files that begin with "=test_*=" will be considered tests.  Tests are automatically run as part of the build procedure (fixme: just C++ ones are automatic right now) and will be rerun when they or code they depend on changes.   When tests are run by the build the =stdout/stderr= is typically captured.  You can run them manually to observe any print statements.  Tests are not installed but left in the "=build/=" (or sometimes "=tmp/=") output directory.

Here are a few general guidelines for writing tests:

 - write many tests
 - write tests as fine grained as convenient
 - the best tests are written before or while the code they test is being written
 - test code does need not be "pretty", it will never be called from anywhere else
 - tests should run quickly
 - do use contrived data or mocked code to provide a bit of test code it's needed input or code support

**** C++ tests

Writing a C++ test is to write a =main()= program which takes *no arguments*.  If a test fails, either let it crash the test program or call =exit(1)=.

You can explicitly run C++ test programs.  When they are run as part of the build, their full path is printed.  When run automatically, waf takes care of setting up their environment so that their libraries are found.  When run manually you will have to assure this.  The simplest way is to "=waf install=" the package first.

#+BEGIN_EXAMPLE
  $ waf
  ...
  execution summary 
    tests that pass 3/4 
      /home/bviren/projects/wire-cell/top/build/data/test_construct 
      /home/bviren/projects/wire-cell/top/build/nav/test_geomdatasource 
      /home/bviren/projects/wire-cell/top/build/sst/test_sst_geomdatasource 
    tests that fail 1/4 
      /home/bviren/projects/wire-cell/top/build/data/test_fail 
  'build' finished successfully (1.594s)

  $ waf install
  $ /home/bviren/projects/wire-cell/top/build/sst/test_sst_geomdatasource 
  Wire: 0 plane=1 index=0
  Wire: 0 plane=1 index=1
  Wire: 0 plane=1 index=2
  ...
#+END_EXAMPLE

